#!/usr/bin/env bash
# Phase 4 Task 7 (T044-T050): backup/restore rehearsal with negative safety
# probes. Starts ONE process-owned disposable PostgreSQL container, applies
# the shipped migrations, seeds a tiny explicit synthetic cohort, then proves:
#   positive: backup archive + verified checksum + fresh-target restore +
#             allowlisted invariants identical between source and target
#   negative: unsafe host, missing PGPASSWORD, missing archive, corrupt
#             archive, target==source, non-disposable name, existing target
#             ALL refuse with the source left unchanged
# Credentials are generated by the OS CSPRNG, exported for the child scripts,
# and NEVER printed. Duration is local training measurement, not SLA/RPO/RTO.
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
cd "$(dirname "$HERE")/../.."

CONTAINER="medicore-phase4-pg-backuprestore"
PORT="55434"
DB_SRC="medicore_phase4_bk_src"
DB_TGT="medicore_phase4_bk_tgt"
DB_USER="medicore_phase4_agent"
OUT_BASE="/tmp/medicore_phase4_backup"
PASS_COUNT=0

ok() { echo "ok: $1"; PASS_COUNT=$((PASS_COUNT+1)); }
deny() { echo "ok(refused): $1"; PASS_COUNT=$((PASS_COUNT+1)); }
cleanup() {
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  docker volume rm "$(docker volume ls -q --filter label=phase4-backup-restore 2>/dev/null)" >/dev/null 2>&1 || true
  rm -f "$OUT_BASE".dump "$OUT_BASE".dump.sha256 /tmp/medicore_phase4_corrupt.dump /tmp/inv_source.txt /tmp/inv_target.txt /tmp/inv_source_again.txt
}
trap cleanup EXIT

# OS CSPRNG credential (never echoed, never persisted).
PGPASSWORD="$(head -c 32 /dev/urandom | base64 | tr -d '\n')"
export PGPASSWORD

echo "== starting disposable container $CONTAINER (loopback:$PORT) =="
docker run -d --name "$CONTAINER" \
  -e POSTGRES_DB="$DB_SRC" -e POSTGRES_USER="$DB_USER" -e POSTGRES_PASSWORD="$PGPASSWORD" \
  -p "127.0.0.1:${PORT}:5432" postgres:16-alpine >/dev/null || { echo "FAIL: container start"; exit 1; }

ready=0
for _ in $(seq 1 60); do
  if pg_isready -h 127.0.0.1 -p "$PORT" -U "$DB_USER" -d "$DB_SRC" >/dev/null 2>&1; then ready=1; break; fi
  sleep 2
done
[ "$ready" -eq 1 ] || { echo "FAIL: disposable postgres never became ready (state: $(docker inspect -f '{{.State.Status}}' "$CONTAINER" 2>/dev/null || echo unknown))"; exit 1; }
ok "disposable postgres ready"

echo "== applying shipped migrations to $DB_SRC =="
"$HERE/migrate-disposable-postgres.sh" 127.0.0.1 "$PORT" "$DB_SRC" "$DB_USER" || { echo "FAIL: migrate"; exit 1; }
ok "migrations applied"

if psql -h 127.0.0.1 -p "$PORT" -U "$DB_USER" -d "$DB_SRC" -v ON_ERROR_STOP=1 -q <<'SQL'
insert into hospital_organizations (id, code, name, created_at, updated_at, version)
 values ('11111111-1111-1111-1111-111111111111','BK-ORG','Synthetic Backup Org',now(),now(),0);
insert into branches (id, organization_id, code, name, location_label, active, created_at, updated_at, version)
 values ('22222222-2222-2222-2222-222222222222','11111111-1111-1111-1111-111111111111','BK-BR','Synthetic Backup Branch','Synthetic Backup Location',true,now(),now(),0);
insert into patients (id, branch_id, medical_record_number, full_name, active, created_at, updated_at, version)
 values ('33333333-3333-3333-3333-333333333333','22222222-2222-2222-2222-222222222222','BK-MRN-0001','Synthetic Backup Patient',true,now(),now(),0);
SQL
then ok "synthetic cohort seeded"
else echo "FAIL: synthetic cohort seed"; exit 1
fi

echo "== positive path =="
"$HERE/backup-postgres.sh" 127.0.0.1 "$PORT" "$DB_SRC" "$DB_USER" "$OUT_BASE" || { echo "FAIL: backup"; exit 1; }
[ -s "$OUT_BASE.dump" ] || { echo "FAIL: archive empty/missing"; exit 1; }
ok "backup archive non-empty"
( cd /tmp && sha256sum -c "$OUT_BASE.dump.sha256" >/dev/null ) && ok "checksum verified"

"$HERE/restore-postgres.sh" 127.0.0.1 "$PORT" "$OUT_BASE.dump" "$DB_TGT" "$DB_USER" || { echo "FAIL: restore"; exit 1; }
ok "restore into fresh disposable target"

"$HERE/verify-database-invariants.sh" 127.0.0.1 "$PORT" "$DB_SRC" "$DB_USER" > /tmp/inv_source.txt || { echo "FAIL: verify source"; exit 1; }
"$HERE/verify-database-invariants.sh" 127.0.0.1 "$PORT" "$DB_TGT" "$DB_USER" > /tmp/inv_target.txt || { echo "FAIL: verify target"; exit 1; }
if diff <(grep '^count ' /tmp/inv_source.txt) <(grep '^count ' /tmp/inv_target.txt) >/dev/null; then
  ok "allowlisted counts identical source vs restored"
else
  echo "FAIL: invariant counts differ"; diff <(grep '^count ' /tmp/inv_source.txt) <(grep '^count ' /tmp/inv_target.txt); exit 1
fi

echo "== negative probes (every one must refuse; source must stay unchanged) =="
"$HERE/backup-postgres.sh" db.internal.example.com "$PORT" "$DB_SRC" "$DB_USER" /tmp/x 2>/dev/null && { echo "FAIL: unsafe host accepted"; exit 1; } || deny "unsafe host backup refused"
( PGPASSWORD= "$HERE/backup-postgres.sh" 127.0.0.1 "$PORT" "$DB_SRC" "$DB_USER" /tmp/x 2>/dev/null ) && { echo "FAIL: missing PGPASSWORD accepted"; exit 1; } || deny "missing PGPASSWORD refused"
"$HERE/restore-postgres.sh" 127.0.0.1 "$PORT" /tmp/does-not-exist.dump medicore_phase4_bk_neg "$DB_USER" 2>/dev/null && { echo "FAIL: missing archive accepted"; exit 1; } || deny "missing archive refused"
head -c 4096 /dev/urandom > /tmp/medicore_phase4_corrupt.dump
"$HERE/restore-postgres.sh" 127.0.0.1 "$PORT" /tmp/medicore_phase4_corrupt.dump medicore_phase4_bk_neg "$DB_USER" 2>/dev/null && { echo "FAIL: corrupt archive accepted"; exit 1; } || deny "corrupt archive refused"
RESTORE_SOURCE_DB="$DB_SRC" "$HERE/restore-postgres.sh" 127.0.0.1 "$PORT" "$OUT_BASE.dump" "$DB_SRC" "$DB_USER" 2>/dev/null && { echo "FAIL: target==source accepted"; exit 1; } || deny "target==source refused"
"$HERE/restore-postgres.sh" 127.0.0.1 "$PORT" "$OUT_BASE.dump" postgres "$DB_USER" 2>/dev/null && { echo "FAIL: non-disposable name accepted"; exit 1; } || deny "non-disposable target name refused"
"$HERE/restore-postgres.sh" 127.0.0.1 "$PORT" "$OUT_BASE.dump" "$DB_TGT" "$DB_USER" 2>/dev/null && { echo "FAIL: overwrite accepted"; exit 1; } || deny "existing-target overwrite refused"
"$HERE/verify-database-invariants.sh" 127.0.0.1 "$PORT" "$DB_SRC" "$DB_USER" > /tmp/inv_source_again.txt || { echo "FAIL: verify source after negatives"; exit 1; }
if diff <(grep '^count ' /tmp/inv_source.txt) <(grep '^count ' /tmp/inv_source_again.txt) >/dev/null; then
  ok "source unchanged after all negative probes"
else
  echo "FAIL: source changed by negative probes"; exit 1
fi

echo "PASS: backup/restore rehearsal — $PASS_COUNT assertions ok"
