import { defineConfig } from '@playwright/test';

// Phase 4 container E2E configuration (T076/T077/T078).
//
// Scope and boundary:
//   - This runner owns NO servers. The disposable Compose review stack
//     (PostgreSQL + backend + frontend, compose.yaml) is started, proven,
//     and torn down by scripts/phase4/container-e2e-stack.sh BEFORE any
//     browser executes (T078). There is deliberately no webServer block:
//     a browser can never accidentally start, reuse, or outlive a stack.
//   - Evidence discipline (T076): trace, screenshots, and video stay OFF.
//     Acceptance comes from assertions, never from captured artifacts.
//   - Credentials (T077): every secret (admin/review passwords, database
//     password, JWT secret) is generated by the OS CSPRNG inside the
//     orchestrating process and exported into THIS process's environment
//     before this config file is even parsed. Nothing is written to disk;
//     a missing variable fails the run here, before any browser starts.
//   - Targets are loopback-only origins handed over by the orchestrator.

const REVIEW_WEB_ORIGIN = process.env.REVIEW_WEB_ORIGIN;
const REVIEW_API_ORIGIN = process.env.REVIEW_API_ORIGIN;

for (const [name, value] of [
  ['REVIEW_WEB_ORIGIN', REVIEW_WEB_ORIGIN],
  ['REVIEW_API_ORIGIN', REVIEW_API_ORIGIN],
  ['HOSPITAL_ADMIN_PASSWORD', process.env.HOSPITAL_ADMIN_PASSWORD],
]) {
  if (!value) {
    throw new Error(
      `Missing environment: ${name} must be exported by scripts/phase4/container-e2e-stack.sh `
        + '(process-local CSPRNG values; never persisted) before running the container E2E suite.'
    );
  }
}

export default defineConfig({
  testDir: 'e2e',
  fullyParallel: false,
  workers: 1,
  forbidOnly: true,
  retries: 0,
  reporter: 'list',
  // The container journey is a long sequential scenario on a single small
  // workstation; resilience rehearsals stop and start real containers.
  timeout: 120_000,
  globalSetup: './e2e/global-setup.mjs',
  // Keep all Playwright output inside the git-ignored node_modules tree.
  outputDir: 'node_modules/.e2e-artifacts',
  use: {
    baseURL: REVIEW_WEB_ORIGIN,
    screenshot: 'off',
    video: 'off',
    // Authenticated network traces can persist disposable credential
    // material. Acceptance here is assertion-only (T076): keep them off.
    trace: 'off',
    extraHTTPHeaders: {},
  },
  projects: [
    {
      name: 'desktop',
      use: { viewport: { width: 1280, height: 720 } },
    },
    {
      name: 'mobile',
      use: {
        viewport: { width: 375, height: 812 },
        isMobile: true,
        hasTouch: true,
      },
    },
  ],
});
