package com.mamtrex.hospital.patient; import com.mamtrex.hospital.audit.AuditService; import com.mamtrex.hospital.auth.ActingContext; import com.mamtrex.hospital.organization.Branch; import com.mamtrex.hospital.organization.BranchRepository; import com.mamtrex.hospital.shared.NotFoundException; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.dao.DuplicateKeyException; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.LocalDate; import java.util.*; @Service @Transactional public class PatientService { private final PatientRepository repo; private final PatientHospitalAccessRepository access; private final BranchRepository branches; private final AuditService audit; public PatientService(PatientRepository r,PatientHospitalAccessRepository a,BranchRepository b,AuditService au){repo=r;access=a;branches=b;audit=au;}
/* Phase 5 US3 (T069; specs/005 data-model.md): one network patient identity. Branch ownership derives from the acting context as before, the network organization derives from that branch, and the create atomically issues exactly one ACTIVE LOCAL_REGISTRATION hospital access grant for the acting hospital — in the same transaction, so a rollback can never leave a grant without its patient. Global MRN uniqueness is unchanged: the pre-check plus the V6-backed unique constraint make a duplicate race produce exactly one winner as the shared 409. */
public Patient create(String mrn,String name,LocalDate dob,String sex,String phone,String email,String nationalId,String address){repo.findByMedicalRecordNumber(mrn).ifPresent(existing->{throw new DuplicateKeyException("Medical record number already exists");});Branch acting=actingBranch();Patient p;try{p=repo.saveAndFlush(new Patient(acting,mrn,name,dob,sex,phone,email,nationalId,address));}catch(DataIntegrityViolationException lostRace){throw new DuplicateKeyException("Medical record number already exists");}access.save(new PatientHospitalAccess(p,acting.getHospital(),PatientAccessSource.LOCAL_REGISTRATION,null));audit.record("CREATE","Patient",p.getId().toString(),mrn);return p;}
/* T070: reads and mutations resolve only inside the acting hospital's ACTIVE access grant (plus the organization pin); a foreign-hospital or unknown id 404s identically. */
@Transactional(readOnly=true) public Patient get(UUID id){return repo.findByIdAndActiveHospitalAccess(id,actingOrganizationId(),actingHospitalId(),PatientAccessStatus.ACTIVE).orElseThrow(()->new NotFoundException("Patient not found: "+id));}
@Transactional(readOnly=true) public List<Patient> list(String q){UUID orgId=actingOrganizationId();UUID hospitalId=actingHospitalId();return q==null||q.isBlank()?repo.findByActiveHospitalAccess(orgId,hospitalId,PatientAccessStatus.ACTIVE):repo.searchByActiveHospitalAccess(orgId,hospitalId,q,PatientAccessStatus.ACTIVE);}
public Patient update(UUID id,String name,String phone,String email,String address){var p=get(id);p.update(name,phone,email,address);audit.record("UPDATE","Patient",id.toString(),"profile");return p;}
private UUID actingOrganizationId(){return actingBranch().getOrganization().getId();}
private UUID actingHospitalId(){return actingBranch().getHospital().getId();}
private Branch actingBranch(){return branches.findById(currentContext().branchId()).orElseThrow(()->new AccessDeniedException("The acting branch is not available"));}
/* Fail-closed seam: the JWT filter guarantees an ActingContext principal and an existing active selected branch for every authorized request; anything else is refused, never guessed. */
private static ActingContext currentContext(){var a=SecurityContextHolder.getContext().getAuthentication();if(a!=null&&a.getPrincipal() instanceof ActingContext c)return c;throw new AccessDeniedException("No acting context is available");} }
